"""Registry of agent tools."""

from . import (
    list_tabs,
    validation,
)

# WS1: Core Infrastructure - Version Token System
from .version import (
    VersionToken,
    TabVersionState,
    VersionManager,
    VersionMismatchError,
    compute_content_hash,
    get_version_manager,
    reset_version_manager,
)

# WS1: Core Infrastructure - Tool Base Classes
from .base import (
    BaseTool,
    ReadOnlyTool,
    WriteTool,
    SubagentTool,
    ToolResult,
    ToolContext,
    DocumentProvider,
    TelemetryEmitter,
)

# WS1: Core Infrastructure - Error Response System
from .errors import (
    ErrorCode,
    ToolError,
    VersionMismatchToolError,
    InvalidVersionTokenError,
    InvalidTabIdError,
    TabNotFoundError,
    DocumentNotFoundError,
    InvalidLineRangeError,
    LineOutOfBoundsError,
    ContentRequiredError,
    InvalidContentError,
    UnsupportedFileTypeError,
    BinaryFileError,
    PatternInvalidError,
    NoMatchesError,
    TooManyMatchesError,
    DocumentLockedError,
    OperationCancelledError,
    TimeoutError,
    InvalidParameterError,
    MissingParameterError,
    error_from_dict,
)

# WS2: Navigation & Reading Tools
from .list_tabs import (
    ListTabsTool,
    TabListingProvider,
    detect_file_type,
    is_supported_file_type,
    create_list_tabs_tool,
)
from .read_document import (
    ReadDocumentTool,
    create_read_document_tool,
    estimate_tokens,
    split_lines,
    CHARS_PER_TOKEN,
    DEFAULT_TOKEN_WINDOW,
    MAX_LINES_PER_RESPONSE,
)
from .search_document import (
    SearchDocumentTool,
    create_search_document_tool,
    search_exact,
    search_regex,
    SearchMatch,
    EmbeddingSearchProvider,
)
from .get_outline import (
    GetOutlineTool,
    create_get_outline_tool,
    OutlineNode,
    detect_markdown_outline,
    detect_json_outline,
    detect_yaml_outline,
    detect_plaintext_outline,
)

# WS3: Writing Tools
from .create_document import (
    CreateDocumentTool,
    DocumentCreator,
    TitleExistsError,
    DocumentCreationError,
    infer_file_type,
    suggest_extension,
)
from .insert_lines import (
    InsertLinesTool,
    DocumentEditor,
    find_anchor_text,
)
from .replace_lines import (
    ReplaceLinesTool,
)
from .delete_lines import (
    DeleteLinesTool,
)
from .write_document import (
    WriteDocumentTool,
)
from .find_and_replace import (
    FindAndReplaceTool,
    ReplacementMatch,
    find_matches_literal,
    find_matches_regex,
    apply_replacements,
)

# WS5: Subagent Architecture
from .subagent import (
    SubagentType,
    TaskPriority,
    ChunkSpec,
    ChunkBoundary,
    SubagentTask,
    SubagentResult,
    ProgressListener,
    ProgressTracker,
    ChunkCoordinator,
    SubagentOrchestrator,
    ResultAggregator,
    AnalysisAggregator,
    TransformAggregator,
    estimate_tokens as subagent_estimate_tokens,
    find_chunk_boundaries,
    split_into_chunks,
)
from .analyze_document import (
    AnalyzeDocumentTool,
    AnalysisType,
    format_analysis_output,
)
from .transform_document import (
    TransformDocumentTool,
    TransformationType,
    OutputMode,
    CharacterRenameSpec,
    ConsistencyIssue,
    find_character_mentions,
    apply_character_rename,
    check_transformation_consistency,
)

# WS6: Tool Registry
from .tool_registry import (
    ToolCategory,
    ParameterSchema,
    ToolSchema,
    ToolRegistration as NewToolRegistration,
    ToolImplementation,
    RegistrationFailure,
    RegistrationError,
    ToolRegistry,
    get_tool_registry,
    reset_tool_registry,
    VERSION_TOKEN_PARAM,
    TAB_ID_PARAM,
    OFFSET_PARAM,
    MAX_LINES_PARAM,
    LIST_TABS_SCHEMA,
    READ_DOCUMENT_SCHEMA,
    SEARCH_DOCUMENT_SCHEMA,
    GET_OUTLINE_SCHEMA,
    CREATE_DOCUMENT_SCHEMA,
    INSERT_LINES_SCHEMA,
    REPLACE_LINES_SCHEMA,
    DELETE_LINES_SCHEMA,
    WRITE_DOCUMENT_SCHEMA,
    FIND_AND_REPLACE_SCHEMA,
    ANALYZE_DOCUMENT_SCHEMA,
    TRANSFORM_DOCUMENT_SCHEMA,
    DIFF_BUILDER_SCHEMA,
    VALIDATE_SNIPPET_SCHEMA,
    ALL_TOOL_SCHEMAS,
)

# WS7: Deprecation & Migration
from .deprecation import (
    LEGACY_TOOL_REPLACEMENTS,
    DeprecatedToolWarning,
    deprecated_tool,
    emit_deprecation_warning,
    get_replacement_tool,
)
from .registry_adapter import (
    NewToolRegistryContext,
    register_new_tools as adapter_register_new_tools,
    get_new_tool_schemas,
)

# WS7: Tool Wiring (extracted from main_window.py)
from .tool_wiring import (
    DocumentBridge,
    WorkspaceProvider,
    SelectionProvider,
    AIControllerProvider,
    ToolWiringContext,
    ToolRegistrationResult,
    register_new_tools as wiring_register_new_tools,
    unregister_tools,
)

__all__ = [
    # Tool modules (kept)
    "list_tabs",
    "validation",
    # Version Token System (WS1.1)
    "VersionToken",
    "TabVersionState",
    "VersionManager",
    "VersionMismatchError",
    "compute_content_hash",
    "get_version_manager",
    "reset_version_manager",
    # Tool Base Classes (WS1.2)
    "BaseTool",
    "ReadOnlyTool",
    "WriteTool",
    "SubagentTool",
    "ToolResult",
    "ToolContext",
    "DocumentProvider",
    "TelemetryEmitter",
    # Error Response System (WS1.3)
    "ErrorCode",
    "ToolError",
    "VersionMismatchToolError",
    "InvalidVersionTokenError",
    "InvalidTabIdError",
    "TabNotFoundError",
    "DocumentNotFoundError",
    "InvalidLineRangeError",
    "LineOutOfBoundsError",
    "ContentRequiredError",
    "InvalidContentError",
    "UnsupportedFileTypeError",
    "BinaryFileError",
    "PatternInvalidError",
    "NoMatchesError",
    "TooManyMatchesError",
    "DocumentLockedError",
    "OperationCancelledError",
    "TimeoutError",
    "InvalidParameterError",
    "MissingParameterError",
    "error_from_dict",
    # Navigation & Reading Tools (WS2)
    "ListTabsTool",
    "TabListingProvider",
    "detect_file_type",
    "is_supported_file_type",
    "create_list_tabs_tool",
    "ReadDocumentTool",
    "create_read_document_tool",
    "estimate_tokens",
    "split_lines",
    "CHARS_PER_TOKEN",
    "DEFAULT_TOKEN_WINDOW",
    "MAX_LINES_PER_RESPONSE",
    "SearchDocumentTool",
    "create_search_document_tool",
    "search_exact",
    "search_regex",
    "SearchMatch",
    "EmbeddingSearchProvider",
    "GetOutlineTool",
    "create_get_outline_tool",
    "OutlineNode",
    "detect_markdown_outline",
    "detect_json_outline",
    "detect_yaml_outline",
    "detect_plaintext_outline",
    # Writing Tools (WS3)
    "CreateDocumentTool",
    "DocumentCreator",
    "TitleExistsError",
    "DocumentCreationError",
    "infer_file_type",
    "suggest_extension",
    "InsertLinesTool",
    "DocumentEditor",
    "find_anchor_text",
    "ReplaceLinesTool",
    "DeleteLinesTool",
    "WriteDocumentTool",
    "FindAndReplaceTool",
    "ReplacementMatch",
    "find_matches_literal",
    "find_matches_regex",
    "apply_replacements",
    # Subagent Architecture (WS5)
    "SubagentType",
    "TaskPriority",
    "ChunkSpec",
    "ChunkBoundary",
    "SubagentTask",
    "SubagentResult",
    "ProgressListener",
    "ProgressTracker",
    "ChunkCoordinator",
    "SubagentOrchestrator",
    "ResultAggregator",
    "AnalysisAggregator",
    "TransformAggregator",
    "subagent_estimate_tokens",
    "find_chunk_boundaries",
    "split_into_chunks",
    "AnalyzeDocumentTool",
    "AnalysisType",
    "format_analysis_output",
    "TransformDocumentTool",
    "TransformationType",
    "OutputMode",
    "CharacterRenameSpec",
    "ConsistencyIssue",
    "find_character_mentions",
    "apply_character_rename",
    "check_transformation_consistency",
    # Tool Registry (WS6)
    "ToolCategory",
    "ParameterSchema",
    "ToolSchema",
    "NewToolRegistration",
    "ToolImplementation",
    "RegistrationFailure",
    "RegistrationError",
    "ToolRegistry",
    "get_tool_registry",
    "reset_tool_registry",
    "VERSION_TOKEN_PARAM",
    "TAB_ID_PARAM",
    "OFFSET_PARAM",
    "MAX_LINES_PARAM",
    "LIST_TABS_SCHEMA",
    "READ_DOCUMENT_SCHEMA",
    "SEARCH_DOCUMENT_SCHEMA",
    "GET_OUTLINE_SCHEMA",
    "CREATE_DOCUMENT_SCHEMA",
    "INSERT_LINES_SCHEMA",
    "REPLACE_LINES_SCHEMA",
    "DELETE_LINES_SCHEMA",
    "WRITE_DOCUMENT_SCHEMA",
    "FIND_AND_REPLACE_SCHEMA",
    "ANALYZE_DOCUMENT_SCHEMA",
    "TRANSFORM_DOCUMENT_SCHEMA",
    "DIFF_BUILDER_SCHEMA",
    "VALIDATE_SNIPPET_SCHEMA",
    "ALL_TOOL_SCHEMAS",
    # WS7: Deprecation & Migration (WS7.1)
    "LEGACY_TOOL_REPLACEMENTS",
    "DeprecatedToolWarning",
    "deprecated_tool",
    "emit_deprecation_warning",
    "get_replacement_tool",
    "NewToolRegistryContext",
    "adapter_register_new_tools",
    "get_new_tool_schemas",
    # WS7: Tool Wiring (WS7.1)
    "DocumentBridge",
    "WorkspaceProvider",
    "SelectionProvider",
    "AIControllerProvider",
    "ToolWiringContext",
    "ToolRegistrationResult",
    "wiring_register_new_tools",
    "unregister_tools",
]
